name: Mini Ecommerce CI/CD

on:

  push:
    branches:
      - main
      - master

  pull_request:
    branches:
      - main
      - master

jobs:

  build-test-and-docker:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: mini-ecommerce

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5

        with:
          go-version: "1.25"

      - name: Install dependencies
        run: go mod tidy

      - name: Run tests
        run: go test ./...

      - name: Build Go application
        run: go build ./cmd/api

        
      - name: Build Docker image
        run: |
          docker build \
          -f deployments/docker/Dockerfile \
          -t mini-ecommerce \
          .

      - name: Pipeline Success
        run: echo "CI pipeline completed successfully"